import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const code=stripTypeScriptTypes(readFileSync(new URL('./src/session-timeline.ts',import.meta.url),'utf8')).replace(/^import .*;\s*/gm,'').replaceAll('export function ','function ');
const scope={};vm.createContext(scope);vm.runInContext(code,scope);
const tracks=['a','b','c'].map(id=>({id,duration:180}));
const first={current_track:'a',next_track:'b',outgoing_transition_timestamp:60,incoming_start_timestamp:40,transition_duration:2,strategy:'local_crossfade'};
const planner=(id,candidates,position)=>{assert.equal(id,'b');assert.equal(position,42);assert.equal(candidates[0],'c');return {...first,current_track:'b',next_track:'c',outgoing_transition_timestamp:100,incoming_start_timestamp:20,strategy:'manual_local_crossfade'};};
const clips=scope.buildTimeline(tracks,'a',0,10,first,['b','c'],planner,{}, {},true,false);
assert.equal(clips.length,3);
assert.equal(clips[0].start,0);assert.equal(clips[0].end,52);
assert.equal(clips[1].start,50);assert.equal(clips[1].cue,40);assert.equal(clips[1].end,112);
assert.equal(clips[2].start,110);assert.equal(clips[2].end,270);assert.equal(clips[1].manual,true);
assert.equal(clips[0].end-clips[1].start,2);
assert.equal(scope.boundedStart(clips[0],180,70,20),80);
assert.equal(scope.boundedStart(clips[0],180,9999,20),179.7);
assert.equal(scope.boundedStart(clips[0],180,-100,20),20.2);
const shifted=scope.buildTimeline(tracks,'a',0,10,{...first,outgoing_transition_timestamp:80},['b','c'],planner,{}, {},true,false);
assert.equal(shifted[1].start,70);assert.equal(shifted[2].start,130);
console.log('Timeline: source/session mapping, overlap alignment, ripple moves, manual labels and playback bounds passed.');
