import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Track = { id:string; title:string; filename:string; duration:number; bpm:number; key:string|null };
type EngineState = { current_track:string; position:number; playing:boolean; auto_dj:boolean; volume:number; queue_order:string[]; upcoming:string[]; transition_state:string; event?:{next_track:string;outgoing_transition_timestamp:number;incoming_start_timestamp:number;transition_duration:number;strategy:string}|null; errors:string[] };
const endpoint = import.meta.env.VITE_ENGINE_URL || 'http://127.0.0.1:8765';
const time = (v:number) => `${String(Math.floor(Math.max(0,v)/60)).padStart(2,'0')}:${String(Math.floor(Math.max(0,v)%60)).padStart(2,'0')}`;
async function api(path:string, init?:RequestInit){const response=await fetch(`${endpoint}${path}`,init);const data=await response.json();if(!response.ok)throw Error(data.error||'Engine request failed');return data;}
function App(){
 const [tracks,setTracks]=useState<Track[]>([]), [state,setState]=useState<EngineState|null>(null), [selected,setSelected]=useState<string>(), [wave,setWave]=useState<number[]>([]), [notice,setNotice]=useState('Connecting to local DJ engine…');
 const byId=(id?:string)=>tracks.find(t=>t.id===id); const send=(action:string, data:Record<string,unknown>={})=>api('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})}).catch(e=>setNotice(e.message));
 useEffect(()=>{let live=true;const poll=async()=>{try{const [library, snapshot]=await Promise.all([api('/api/library'),api('/api/state')]);if(!live)return;setTracks(library);setState(snapshot.state);setNotice(snapshot.ready?'Local engine connected':'Local engine unavailable');if(!selected&&library[0])setSelected(library[0].id);}catch{if(live){setState(null);setNotice('Local DJ engine unavailable — run `python -m ai_dj ui` on the playback computer.');}}};poll();const timer=setInterval(poll,250);return()=>{live=false;clearInterval(timer)}},[selected]);
 useEffect(()=>{if(!selected)return;api(`/api/waveform/${encodeURIComponent(selected)}`).then(d=>{if(d.peaks)setWave(d.peaks)}).catch(()=>setWave([]))},[selected]);
 const current=byId(state?.current_track), cue=byId(selected); return <main>
  <header><h1>SYNC <small>LIVE DJ</small></h1><span className={state?'connected':''}>● {notice}</span></header>
  <section className="player"><div><label>NOW PLAYING</label><h2>{current?.title||'No local engine connected'}</h2><p>{current?.filename||'The web UI never accesses music files directly.'}</p></div><div className="transport"><button onClick={()=>send('previous')}>Ⅰ◀</button><button className="play" onClick={()=>send(state?.playing?'pause':'play')}>{state?.playing?'Ⅱ':'▶'}</button><button onClick={()=>send('next')}>▶Ⅰ</button><button onClick={()=>send('stop')}>■</button></div><label className="volume">VOL <input type="range" min="0" max="1" step=".01" value={state?.volume??1} onChange={e=>send('volume',{value:+e.target.value})}/></label><div className="seek"><time>{time(state?.position||0)}</time><input type="range" min="0" max={current?.duration||1} step=".01" value={state?.position||0} onChange={e=>send('seek',{seconds:+e.target.value})}/><time>−{time((current?.duration||0)-(state?.position||0))}</time></div></section>
  <section className="timeline"><div className="section-title"><h2>Live timeline</h2><span>{state?.event?`${state.event.strategy.startsWith('manual_')?'MANUAL':'AUTO'} · EXIT ${time(state.event.outgoing_transition_timestamp)} · CUE ${time(state.event.incoming_start_timestamp)}`:'Preparing next deck'}</span><button onClick={()=>state&&send('auto',{enabled:!state.auto_dj})}>AUTO DJ · {state?.auto_dj?'ON':'OFF'}</button></div><div className="lane"><div className="bar current" style={{width:`${Math.max(18,100*(1-(state?.position||0)/(current?.duration||1)))}%`}}>{current?.title||'Current track'}</div><div className="bar incoming" style={{width:`${Math.max(15,100*((state?.event?.transition_duration||2)/(current?.duration||120)))}%`}}>{byId(state?.event?.next_track)?.title||'Incoming track'}</div><i style={{left:`${Math.min(99,100*(state?.position||0)/(current?.duration||1))}%`}}/></div></section>
  <div className="columns"><section><div className="section-title"><h2>Library <small>{tracks.length}</small></h2></div>{tracks.map(t=><button className={`row ${selected===t.id?'selected':''}`} key={t.id} onClick={()=>setSelected(t.id)}><b>{t.title}</b><span>{t.bpm} · {t.key||'—'}</span><time>{time(t.duration)}</time><em onClick={e=>{e.stopPropagation();send('queue',{tracks:[...(state?.queue_order||[]).filter(id=>id!==t.id),t.id]})}}>+</em></button>)}</section><section><div className="section-title"><h2>Queue <small>{state?.queue_order.length||0}</small></h2></div>{(state?.queue_order||[]).map((id,i)=><div className={`row queue ${id===state?.current_track?'selected':''}`} key={id}><small>{String(i).padStart(2,'0')}</small><b>{byId(id)?.title||id}</b><button onClick={()=>send('next',{track:id})}>▶</button></div>)}</section></div>
  <section className="cue"><div className="section-title"><div><label>CUE EDITOR</label><h2>{cue?.title||'Select a track'}</h2></div><button disabled={!selected} onClick={()=>selected&&send('next',{track:selected})}>Load track</button></div><div className="wave">{wave.length?wave.map((v,i)=><i key={i} style={{height:`${Math.max(3,v*100)}%`}}/>):<span>Audio waveform will load from the local engine</span>}</div><p>Click/select a track above. Cue editing stays inside the local engine boundary.</p></section>
  <footer>{state?.errors?.at(-1)||notice}<span>Frontend deployment is independent of Python audio runtime</span></footer>
 </main>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
